### ISSUE TITLE
error on ToggleMarkbar

### ISSUE THREAD

**Issue by samf** [Yilin-Yang/vim-markbar#1]
I just installed, and set up `<leader>m to` `<Plug>ToggleMarkbar`. I got this error when I tried it:

```
Error detected while processing function markbar#ui#ToggleMarkbar[1]..markbar#MarkbarState#toggleMarkbar[3]..markbar#MarkbarState#openMarkbar[16]..markbar#MarkbarState#p
opulateWithMarkbar[5]..markbar#MarkbarState#getMarkbarContents:
line   19:
E716: Key not present in Dictionary: a
E15: Invalid expression: markbar#helpers#IsGlobalMark(l:mark_char) ? l:globals[l:mark_char] : l:marks[l:mark_char]
Error detected while processing function markbar#ui#ToggleMarkbar[1]..markbar#MarkbarState#toggleMarkbar[3]..markbar#MarkbarState#openMarkbar[16]..markbar#MarkbarState#p
opulateWithMarkbar:
line    5:
E734: Wrong variable type for +=
```

**Comment by samf** [comment]
I forgot to mention, I did a `ma` to set a mark before doing this. So I should have had one mark named "a".

**Comment by kcoyner** [comment]
I have experienced exactly the same issue.  I like the concept and look forward to seeing it working.

**Comment by dsanson** [comment]
Me too

**Comment by Yilin-Yang** [comment]
Hey, guys:

Sorry to hear that the plugin is giving you trouble. I can't reproduce this behavior on my machine; if you're able, could you post the following:

- The output of `vim --version` (or `nvim --version`, if you use neovim)
- The smallest `.vimrc` with which you're able to reproduce the problem
- Steps to reproduce (e.g. were you trying to set a mark in an unnamed buffer after opening vim with `vim`, etc.)

The reason I ask for a "minimal .vimrc" is that vim-markbar can exhibit strange behavior when used alongside other "sidebar" plugins (like tagbar and fzf.vim), though I've only seen that when I tried using them simultaneously (e.g. opening fuzzyfind with the markbar open).

Also, could you try executing `:call g:markbar_buffers['updateCurrentAndGlobal()']()` before opening the markbar, and see if it produces the same error message? markbar should do this automatically, but it might not be doing that on your guys' machines.

**Comment by dsanson** [comment]
I get the problem on both nvim and vim (both running a shared `.vimrc`)

```
> nvim --version
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/config -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20180721-48604-1emkq4l/neovim-0.3.1/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui 
```
```
> vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  7 2018 21:58:18)
macOS version
Included patches: 1-250
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary  
```

My `.vimrc` is complicated enough that I am not going to be able easily to provide you with a minimal `.vimrc` that causes the problem. I did verify that the problem goes away if I remove everything but the stuff that loads markbar, so it must be that it conflicts with something in my `.vimrc`. Here are the plugins I have installed:

```
Plug 'mtth/scratch.vim'
Plug 'justinmk/vim-gtfo'
Plug 'dag/vim-fish'
Plug 'tomtom/tcomment_vim'
Plug 'ervandew/supertab'
Plug 'vim-scripts/DrawIt'
Plug 'vim-scripts/RST-Tables'
Plug 'lervag/vimtex'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'   
Plug 'vim-pandoc/vim-pandoc'
Plug 'vim-pandoc/vim-pandoc-syntax'
Plug 'chrisbra/csv.vim'
Plug 'jszakmeister/vim-togglecursor'
Plug 'tpope/vim-dispatch'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'rking/ag.vim' 
Plug 'reedes/vim-litecorrect'
Plug 'altercation/vim-colors-solarized'
Plug 'lifepillar/vim-solarized8'
Plug 'morhetz/gruvbox'
Plug 'romainl/Apprentice'
Plug 'justinmk/vim-sneak'
Plug 'junegunn/goyo.vim'
Plug 'dearrrfish/vim-applescript'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/vim-easy-align'
Plug 'junegunn/seoul256.vim'
Plug 'rhysd/vim-grammarous'
Plug 'aperezdc/vim-template/'
Plug 'Yilin-Yang/vim-markbar'
```

I get the problem when I attempt to toggle the markbar while viewing a file that contains marks. The problem goes away if the file contains no marks.

I tried executing `:call g:markbar_buffers['updateCurrentAndGlobal()']()` first, and that made no difference.

**Comment by Yilin-Yang** [comment]
Still no luck replicating the bug on my end, unfortunately. :( I tried using vim/nvim and using a `.vimrc` that only installed those plugins (using vim-plug, into a different directory than my usual `~/.vim/bundle`), but the markbar still opens for me without issue.

I don't suppose you'd be willing to provide your `.vimrc` (in a `.tar.gz` file, PasteBin, etc.)? You wouldn't have to worry about "fixing" it (e.g. removing absolute filepaths, removing references to WIP-plugins on your machine, etc.); I can comment out any lines that cause problems. No pressure, though, if that would be inconvenient for you; you've already been very helpful!

**Comment by dsanson** [comment]
I think the problem is caused by `set ignorecase`. Here is a minimal .vimrc that causes the problem for me on nvim:

```
call plug#begin('~/.vim/plugged')
Plug 'Yilin-Yang/vim-markbar'
call plug#end()
map ,m <Plug>ToggleMarkbar
set ignorecase
```

I can also remove the problem using my usual .vimrc by toggling `ignorecase` off, and then bring it back by toggling `ignorecase` on.

**Comment by Yilin-Yang** [comment]
Got it! Was able to replicate the issue on my machine, and I think I've fixed it.

I've pushed the changes to the `dev` branch. Could you check it out and see if the error's gone away?

**Comment by dsanson** [comment]
Yes! Fixed it for me.

**Comment by Yilin-Yang** [comment]
No problem! And thanks again, for your help!
