### ISSUE TITLE
Specifying unset mark results in two prompts

### ISSUE THREAD

**Issue by jcrd** [Yilin-Yang/vim-markbar#10]
Using `'q`:
```
Mark not set: q
Press any key to continue.
Press ENTER or type command to continue
```
The second prompt occurs after responding to the first.

**Comment by Yilin-Yang** [comment]
Just pushed some changes to the `issue_10` branch! Could you pull from the branch and see if it fixes things?

**Comment by jcrd** [comment]
It's fixed, thanks.
