### ISSUE TITLE
window-local working directories can cause error "Window does not exist"

### ISSUE THREAD

**Issue by andreasthoelke** [Yilin-Yang/vim-markbar#12]
When working with window-local working directories (via `:lcd`) I run into the following error.

Steps to reproduce:
``` vim
cd ~
vim
:e .vimrc
:lcd . "Setting a window-local working directory in the initial tab is needed to reproduce the error 
:tabe .vim/plugged/vim-markbar/plugin/vim-markbar.vim
" At this stage <Plug>OpenMarkbar, <Plug>CloseMarkbar works fine
lcd .vim/plugged/vim-markbar/
" Now <Plug>OpenMarkbar causes this error:
```
```
Error detected while processing function markbar#MarkbarController#toggleMarkbar[3]..markbar#MarkbarController#openMarkbar[6]..markbar#StandardMarkbarController#_openMarkbarSplit[3]..markbar#MarkbarView#openMarkbar[16]..markbar#MarkbarView#_setMarkbarWindowSettings:
line    7:
E605: Exception not caught: (MarkbarView#_setMarkbarWindowSettings) Window does not exist for: 3
```
I can reproduce this in current vim and neovim versions:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 16 2018 18:20:26)
macOS version
Included patches: 1-400
```
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
```
I have had similar issues with nvim's `tcd`/ tab-local working directories.

**Comment by Yilin-Yang** [comment]
Hey Andreas,

Thanks for the report! I was able to reproduce the bug on my machine, and I've pushed some changes to `issue_12` that should hopefully fix things. Would you mind cloning from that branch and seeing if the issue is resolved on your machine?

Best,
Yilin

**Comment by andreasthoelke** [comment]
@Yilin-Yang I tested the issue_12 branch running through typical uses of `lcd` and `tcd` and everything worked fine. I think this fixes the issue. 

Thank you for fixing this so quickly!
