### ISSUE TITLE
See special marks in the bar

### ISSUE THREAD

**Issue by davidsierradz** [Yilin-Yang/vim-markbar#13]
Hi, nice plugin!

I have this in my `init.vim`.

```vim
let g:markbar_marks_to_display = "'.[]<>^abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

let g:markbar_peekaboo_marks_to_display = "'.[]<>^abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
```

Is there a way to see special marks like `.`, `[`, etc...?

Thanks!

**Comment by Yilin-Yang** [comment]
Hey, David!

Setting `g:markbar_[peekaboo_]marks_to_display` as you did should have been enough to enable special marks, according to the docs I wrote, but after trying it myself, I realized that it didn't! I think this was an issue I'd noticed during development, added to my "To-Do" list, but never actually gotten around to fixing.

I've pushed some changes to the `issue_13` branch that should fix this; could you pull from that branch and see if it works on your machine?

Best,
Yilin
