### ISSUE TITLE
Feature request - separate context var by mark type

### ISSUE THREAD

**Issue by curioussavage** [Yilin-Yang/vim-markbar#14]
I think it would be nice to not have any context for File marks but have some for local ones. The only important thing to me for file marks is the file name itself.
So there could be `g:markbar_num_lines_context_local` and `g:markbar_num_lines_context_global` or whatever you want to call it.

**Comment by Yilin-Yang** [comment]
Howdy!

This is on my to-do list, though I might not get around to it for a little while (~weeks). I'll ping you once I have something ready for testing!

**Comment by Yilin-Yang** [comment]
Just pushed some changes to the branch `config_context`, if you'd like to take a look! Please let me know if you encounter any issues.

To obtain the behavior you mentioned in your first post, try setting this in your vimrc:

```vim
let g:markbar_num_lines_context = {
  \ 'around_local': 5,
  \ 'around_file': 0,
  \ }
```

**Comment by Yilin-Yang** [comment]
I've been using the changed code myself for a little while and verified that it works (at least for me), so I've gone ahead and merged this into the master branch. Let me know if there's anything else!

**Comment by curioussavage** [comment]
Awesome! I'll try and test it out asap!
