### ISSUE TITLE
E117: Unknown function: deletebufline

### ISSUE THREAD

**Issue by Blake-LeBlanc** [Yilin-Yang/vim-markbar#15]
Hello! 

Whenever I toggle the plugin with `<leader>m`, I receive the following error:

```
"( Markbar )"  --No lines in buffer--
Error detected while processing function markbar#PeekabooMarkbarController#backtick[4]..markbar#MarkbarController#openMarkbar[10]..markbar#MarkbarController#refreshContents[9]..markbar#MarkbarController#_populateWithMarkbar[7]..markbar#helpers#ReplaceBuffer[1]..markbar#helpers#SetBufferLineRange:
line   20:
E117: Unknown function: deletebufline
```
Once I press <CR> to continue out of the message, the Markbar **does** display, but it does not list any active marks.

And when I press the toggle it off, it goes away with any further error messages.

If it's of any use, I do have junegunn's vim-peekaboo installed and enabled.

Please let me know if there is any more information you need, I'm happy to help :)

Thank you!

**Comment by Yilin-Yang** [comment]
Hi, Blake!

Thanks for the report! Can you let me know what version of vim you're using? vim-markbar currently requires patches up to [8.1.0039](https://github.com/vim/vim/commit/d79a26219d7161e9211fd144f0e874aa5f6d251e) (which adds the `deletebufline()` function) in order to function properly, or neovim.

Thanks!

**Comment by Blake-LeBlanc** [comment]
Thank you Yilin-Yang, switching over to neovim did the trick!

As you suspected, I was on an older version of vim (sorry I didn't first check your well-written documentation). Switching over to the typevim branch and including those extra plugins DOES get it to work vim 8.0 as well.

Thanks again for your great support!

**Comment by Yilin-Yang** [comment]
It's my pleasure! 😀
