### ISSUE TITLE
vim-markbar breaks 'mark' in 'foldopen'

### ISSUE THREAD

**Issue by nkakouros** [Yilin-Yang/vim-markbar#18]
When vim-markbar is installed, jumping to a mark that lies in closed fold does not cause the fold to open. This behavior is controlled in vim via the `foldopen` setting. Specifying `mark` in the `foldopen` does not solve the problem as `vim-markbar` seems to neglect the setting.

**Comment by Yilin-Yang** [comment]
Hi @nkakouros,

Sorry for the outrageously long delay in response! I've just pushed some changes to branch `foldopen`: could you pull from that branch and see if it fixes the issue?

Best,
Yilin

**Comment by Yilin-Yang** [comment]
Hi nkakouros,

Since it's been a few days, and because the fix feels like a low-risk code change, I'll be merging this into master and closing this issue for now. If you run into further issues, or if this wasn't what you were expecting, feel free to comment again and reopen the issue.

Best,
Yilin
