### ISSUE TITLE
Killing markbar buffer with bd causes exceptions when opening again.

### ISSUE THREAD

**Issue by thedracle** [Yilin-Yang/vim-markbar#2]
First of all, great work! 

This is really a super intuitive thing that I'm surprised didn't already exist for Vim.

One little issue is that if I use :bd to kill the popup, subsequently opening the markbar causes the following exceptions:

```
Error detected while processing function markbar#ui#ToggleMarkbar[1]..markbar#MarkbarState#toggleMarkbar[3]..markbar#MarkbarState#openMarkbar[8]..markbar#ui#OpenMarkbarSplit[17].
.markbar#ui#SetMarkbarMappings[3]..markbar#ui#SetGoToMark[1]..<SNR>200_CheckBadBufferType:
line    2:
E605: Exception not caught: (vim-markbar) Cannot invoke this function outside of a markbar buffer/window!
Error detected while processing function markbar#ui#ToggleMarkbar[1]..markbar#MarkbarState#toggleMarkbar[3]..markbar#MarkbarState#openMarkbar:
line    8:
E171: Missing :endif
```

**Comment by Yilin-Yang** [comment]
Thank you for the report, and for the kind words! My classes have started, so I won't be able to work on this right away, but I'll look into it as soon as I'm able.

**Comment by Yilin-Yang** [comment]
Just pushed some changes to the `dev` branch: could you check it to see if the error's been fixed on your end?

I'm also doing some heavy refactoring/dev work on the `mvc` branch, which should (if everything goes as expected) be merged into the mainline branches soon-ish. From my testing, it looks like this issue doesn't occur on that branch, but the changes I've made might've broken something else: would you be willing to check that branch as well?

**Comment by thedracle** [comment]
Thanks Yilin, your fix works perfectly!

**Comment by thedracle** [comment]
I also checked on the mvc branch, and it seems to be fixed there as well.
