### ISSUE TITLE
Implementing Force Delete Option for Neovim Users to Ensure Marks Stay Deleted

### ISSUE THREAD

**Issue by p0da** [Yilin-Yang/vim-markbar#20]
Would you consider adding the same option that vim-signature added in https://github.com/kshenoy/vim-signature/issues/72? Also thanks for all your work, this plugin is an essential part of my vim config.

**Comment by Yilin-Yang** [comment]
Hi, sorry for the delay, and thanks for the kind words. Reopening this issue; I'm open to working on this.
