### ISSUE TITLE
Error after plugging vim-markbar with both vim and neovim

### ISSUE THREAD

**Issue by francomarianardini** [Yilin-Yang/vim-markbar#38]
Hello,

thanks a lot for the effort you put in writing this cool plugin.

I am installing vim-markbar on both vim v.8.2.5100 and neovim v.0.7.0 using vim-plug (https://github.com/junegunn/vim-plug), latest version.

After installation, on both editors in the command bar I see

Error detected while processing function MarkbarVimEnter[6]..markbar#settings#PersistMarkNames:
line   20:
(vim-markbar) WARNING: g:markbar_persist_mark_names is v:true, but won't work because viminfo-!/shada-! is not set! `set viminfo+=!` in vim or `set shada+=!` in neovim to fix this.
Press ENTER or type command to continue

Is it a bug?

thanks, best,

Franco Maria

**Comment by Yilin-Yang** [comment]
Hello!

By default, vim-markbar tries to store the user's mark names in the viminfo file (in vim) or the shada file (in neovim), but this only works if the `viminfo`/`shada` setting includes `!`. `:help viminfo-!` in vim and `:help shada-!` in neovim gives more information on what this means: in essence, including `!` in `viminfo`/`shada` will make (neo)vim remember variables with all-caps names between editor sessions.

Does your .vimrc have a line like `set viminfo+=!` or `set shada+=!`? Alternatively, what do you see when you enter `:echo &viminfo` (from vim) or `:echo &shada` (from neovim)?

If you don't care about whether mark names persist between editing sessions, you can also just add `let g:markbar_persist_mark_names = v:false` to your .vimrc to silence the error message.

**Comment by Yilin-Yang** [comment]
I've realized that I haven't answered your question, sorry. 😅

That's not a bug; it's a warning that one of vim-markbar's features won't work unless you change some of vim's settings.

If you add the following lines to your `.vimrc`, then the error message should go away:

```vim
if has('nvim')
    set shada+=!
else
    set viminfo+=!
endif

" OR,

let g:markbar_persist_mark_names = v:false
```

If that doesn't work, and you still see the error message after adding those lines to your `.vimrc`, then it's a bug.

**Comment by francomarianardini** [comment]
thanks a lot Yilin

I added "let g:markbar_persist_mark_names = v:false" to my .vimrc but I still receive an error (different from before). Then I realized I had the "set viminfo=""" option to avoid having a viminfo file. Once removed, everything works smooth. However, maybe you want to cross-check the behavior with no viminfo file. That part seems not to work even if you add "let g:markbar_persist_mark_names = v:false".

Thanks a lot for your help. best,

FM

**Comment by Yilin-Yang** [comment]
Glad to hear that things are working now!

Could you post the different error message that you were seeing? I tried setting `set viminfo=""` and in my own .vimrc (and `set shada=` with nvim, etc.), but didn't see any error message with `let g:markbar_persist_mark_names = v:false` set.

**Comment by francomarianardini** [comment]
thanks Yilin,

I currently have:

`set viminfo=""` and `let g:markbar_persist_mark_names = v:false`.

when I toggle the markbar with:

`nmap <C-m><C-m> <Plug>ToggleMarkbar`

I see

`Error detected while processing function <SNR>20_ToggleMarkbar[4]..<SNR>20_OpenMarkbar[2]..markbar#MarkbarController#openMarkbar[1]..markbar#MarkbarModel#updateCurrentAndGlobal[26]..markbar#helpers#
GetLocalMarks[9]..function <SNR>20_ToggleMarkbar[4]..<SNR>20_OpenMarkbar[2]..markbar#MarkbarController#openMarkbar[1]..markbar#MarkbarModel#updateCurrentAndGlobal[26]..markbar#helpers#GetLocalMarks:

E121: Undefined variable: s:ftype_out`

that's the error I was mentioning in the previous post.

thanks Yilin.

best,

FM

**Comment by Yilin-Yang** [comment]
Gotcha, thanks for the info!

That looks like #33 cropping up. I can work on fixing that on my end. Do you have preservim/tagbar installed by any chance?

**Comment by Yilin-Yang** [comment]
I just pushed some code to the `dev` branch (commit e06136955595be20f1a5b75d7fd0382d854d574b). Could you try using that code with:

```vim
" in .vimrc
Plug 'Yilin-Yang/vim-markbar', { 'branch': 'dev' }
```

And see if that error message goes away?

**Comment by Yilin-Yang** [comment]
Also (sorry for the spam): If you could post your .vimrc, I'd appreciate it. I think that the message you're seeing is partly an upstream issue with (neo)vim itself, and having your .vimrc should help me figure out a minimal repro for it.

**Comment by francomarianardini** [comment]
after moving to the dev branch and re-installing the plugin, issue solved! 

thanks a lot Yilin!

do you still need my .vimrc?

thanks! best

FM

**Comment by francomarianardini** [comment]
ps: yes, I am using tagbar, BTW.

best,

FM

**Comment by Yilin-Yang** [comment]
Fantastic! I'll go ahead and merge that code into master.

I don't need your .vimrc anymore; I was able to find a small repro in the time since I last posted. Thanks for your help!

**Comment by francomarianardini** [comment]
thanks Yilin!
