### ISSUE TITLE
vim-markbar plugin breaks used with "vim-markdown-folding-master"

### ISSUE THREAD

**Issue by jackanory101** [Yilin-Yang/vim-markbar#50]
Latest Markbar plugin breaks badly when used with latest version of [vim-markdown-folding](https://github.com/masukomi/vim-markdown-folding) plugin. Running Gvim 8.1.

Attached video capture shows effect of jumping to mark via 1) suggested mapping `<Leader>m`, and 2) via peekaboo master `'` in markdown file. 

Plugin [vim-markdown-folding](https://github.com/masukomi/vim-markdown-folding) plugin works OK. 

NOTE: I uninstalled ALL plugins to isolate issue and can say that only when Markdown-folding plugin installed is there a problem. 

https://github.com/Yilin-Yang/vim-markbar/assets/57606261/becbf826-8a34-4acf-8974-8382ea56294b

**Comment by Yilin-Yang** [comment]
Thanks for the report, @jackanory101. I wasn't able to reproduce the issue on my end with neovim v0.9.0, vim 8.1.0039, vim 8.2, or gVim 8.2.

That said, the recording you provided reminds me of Issue #27, where vim-markbar opened the target buffer inside the markbar, but I've never seen the markbar open from inside the target window. I wonder if there's a bug in the specific vim version that you're using that doesn't occur elsewhere in the git history.

Does the issue persist when you try different vim versions (both terminal vim vs. windowed vim, and between different version numbers)? And, could you post the vim-markbar settings and mappings that you're using when the issue occurs?

**Comment by jackanory101** [comment]
Tested both Markbar and Markdown-folding together with Gvim 9.0. No problem. Probably not worth doing further testing on this. Sorry for the fuss. :)
