### ISSUE TITLE
bunload-ing and :ls! unlisted buffer command

### ISSUE THREAD

**Issue by jackanory101** [Yilin-Yang/vim-markbar#55]
If I edit several files in one gvim window (8.1) and `bunload` them, they appear in subsequent gvim windows via `:ls!` command as unlisted buffers. 

This is the case if I simply `:e` the file, then `:bunload` it. I don't do anything with marks. 

If I disable the vim-markbar plugin (updated and tested today), the `bunload`-ed buffer does not appear in `:ls!` command in new gvim window.

**Comment by Yilin-Yang** [comment]
Hi Jack, thanks for the bug report!

I'm having some trouble reproducing this issue on my machine. When I try `:bunload`ing a file with no plugins active as a control, the unloaded buffer still appears in the buffer list even without the `!` flag.

```
bash $ ~/out/vim8.1.0039/bin/vim -u NONE -O LICENSE README.md plugin/vim-markbar.vim
:ls
  1 %a   "LICENSE"                      line 1
  2  a   "README.md"                    line 0
  3  a   "plugin/vim-markbar.vim"       line 0
:bunload 3
:ls!
  1 %a   "LICENSE"                      line 2
  2  a   "README.md"                    line 0
  3      "plugin/vim-markbar.vim"       line 0
:ls
  1 %a   "LICENSE"                      line 1
  2  a   "README.md"                    line 0
  3      "plugin/vim-markbar.vim"       line 0
```

I see the same behavior in a recent build of neovim with markbar enabled:

```
bash $ nvim -O LICENSE README.md plugin/vim-markbar.vim
:version
NVIM v0.10.0-dev-1194+gcfb898cd8
Build type: Release
LuaJIT 2.1.0-beta3
Run ":verbose version" for more info
:ls
  1 %a   "LICENSE"                      line 1
  2  a   "README.md"                    line 0
  3  a   "plugin/vim-markbar.vim"       line 0
:bunload 3
:ls
  1 %a   "LICENSE"                      line 2
  2  a   "README.md"                    line 0
  3      "plugin/vim-markbar.vim"       line 0
:ls!
  1 %a   "LICENSE"                      line 2
  2  a   "README.md"                    line 0
  3      "plugin/vim-markbar.vim"       line 0
  4u h   "[Scratch]"                    line 0
  5u     "~/eecs484/caen/eecs484_p1/createTables.sql" line 1
  6u     "~/eecs485/eecs485_p1/insta485/templates/base.html.jinja2" line 1
  [snip, other school projects]
```

Could you provide more detailed reproduction steps? Does the issue go away if you use a newer version of vim?

**Comment by jackanory101** [comment]
I'm sorry for the bother. I've updated vim and no longer have an issue.
