### ISSUE TITLE
vim-markbar may be incompatible with vim-signature?

### ISSUE THREAD

**Issue by andrewferrier** [Yilin-Yang/vim-markbar#8]
I've been seeing random bugs related to Netrw and markbar for a few weeks. I think I've isolated the problem a bit...

To recreate:

nvim v0.3.1 on OS X (exact version/OS probably doesn't matter).

With a `~/.config/nvim/init.vim` of:

```
call plug#begin()
Plug 'tpope/vim-vinegar'
Plug 'kshenoy/vim-signature'
Plug 'Yilin-Yang/vim-markbar'
call plug#end()
```

(and vim-plug installed, i.e. https://github.com/junegunn/vim-plug/blob/master/plug.vim in `~/.config/nvim/autoload` - although I suspect the plugin manager doesn't matter).

I open nvim just by typing `nvim`. I hit `-` twice to navigate up to the parent directory, then again for its parent (this is a feature `vim-vinegar` provides but I don't think it's directly related to the bug as I've seen it in other places, just not easily recreatable).

I now see an error that looks like this:

```
Error detected while processing function <SNR>9_opendir[7]..<SNR>48_NetrwBrowseUpDir[50]..<SNR>48_NetrwBrowseChgDir[282]..markbar#Pe
ekabooMarkbarController#backtick[3]..markbar#MarkbarController#openMarkbar[11]..markbar#MarkbarController#_populateWithMarkbar[3]..m
arkbar#PeekabooMarkbarController#_getMarkbarContents[2]..markbar#MarkbarController#_generateMarkbarContents:
line    6:
E716: Key not present in Dictionary: 1
E15: Invalid expression: l:buffer_caches[a:buffer_no]['_marks_dict']
Error detected while processing function <SNR>9_opendir[7]..<SNR>48_NetrwBrowseUpDir[50]..<SNR>48_NetrwBrowseChgDir[282]..markbar#Pe
ekabooMarkbarController#backtick[3]..markbar#MarkbarController#openMarkbar[11]..markbar#MarkbarController#_populateWithMarkbar:
line    3:
E734: Wrong variable type for +=
```

Judging by the error, it looks like some interaction error between `vim-signature` and `vim-markbar`, but I'm not sure which is at fault. Sorry I haven't dug any further.

Thanks again for all your work on `vim-markbar` - great plugin!

**Comment by andrewferrier** [comment]
I should add that the plugin commits are as follows:

* vim-signature: 6bc3dd1294a2
* vim-markbar: 98aeac7a52b7b
* vim-vinegar: c38ea2195a43747

I think they are all the latest at time of writing.

**Comment by Yilin-Yang** [comment]
Thanks for the report! I've been able to replicate this on my machine, and I'll start working on a fix!

**Comment by Yilin-Yang** [comment]
I think I've tracked down the issue!

Based on the callstack in the error message you posted, line 282 in Netrw's `s:NetrwBrowseChgDir` function is trying to open the 'backtick' peekaboo markbar, which causes an error.

That turns out to be line 4780 in `[n]vim/runtime/autoload/netrw.vim`, which happens to be:
```vim
   endif
   NetrwKeepj call s:SetRexDir(a:islocal,dirname)
   norm m` " <-- this one

  elseif exists("w:netrw_liststyle") && w:netrw_liststyle == s:TREELIST && exists("w:netrw_treedict")
```

I'm still not sure why this line only throws an error if vim-signature is enabled, but changing that line to `` norm! m` `` (as is done elsewhere in that same file) fixes the issue on my machine.

The elegant/permanent fix for this problem is probably involves opening a pull request in the vim/neovim repos, but since that might take a while, I'll see if I can figure out how to "hide" markbar from Netrw in the meantime!

**Comment by Yilin-Yang** [comment]
Just pushed a fix to `issue_8`! When you have the time, could you pull from that branch and see if it fixes the issue?

Thanks so much for your help!

**Comment by andrewferrier** [comment]
Just tested this. Works perfectly! Thanks again for the very prompt response.

**Comment by Yilin-Yang** [comment]
It's my pleasure! 😄
